// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm_2vvPpwA63ssor2pfN_taOME3F8w8Ow',
    appId: '1:736018382077:web:37cdf29b36606f616dd294',
    messagingSenderId: '736018382077',
    projectId: 'wadachi-d93da',
    authDomain: 'wadachi-d93da.firebaseapp.com',
    storageBucket: 'wadachi-d93da.appspot.com',
    measurementId: 'G-ETBLVG5DLJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2uC8SwyEhzR3VFmGoriOnIbn1nBuWk9c',
    appId: '1:736018382077:android:cc77e7038bc272086dd294',
    messagingSenderId: '736018382077',
    projectId: 'wadachi-d93da',
    storageBucket: 'wadachi-d93da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYvdbzVsaKu9YIOcLvnpVQThP_Qn1_fiM',
    appId: '1:736018382077:ios:18744d7e8da6b8176dd294',
    messagingSenderId: '736018382077',
    projectId: 'wadachi-d93da',
    storageBucket: 'wadachi-d93da.appspot.com',
    iosClientId: '736018382077-2d91cg3i1l882ql4i35qfo63cbfdbtdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYvdbzVsaKu9YIOcLvnpVQThP_Qn1_fiM',
    appId: '1:736018382077:ios:18744d7e8da6b8176dd294',
    messagingSenderId: '736018382077',
    projectId: 'wadachi-d93da',
    storageBucket: 'wadachi-d93da.appspot.com',
    iosClientId: '736018382077-2d91cg3i1l882ql4i35qfo63cbfdbtdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.counterFirebase',
  );
}
